version: '3.4'
services:
  java8:
    container_name: wiris-java-8
    image: tomcat:8.5.43-jdk8-openjdk
    volumes:
      # Add Catalina configuration to create a user and disable a few security policies.
      - "./catalina/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
      - "./catalina/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml"
      - "./catalina/web.xml:/usr/local/tomcat/webapps/manager/WEB-INF/web.xml"
    environment:
      - EDITOR
    ports:
      - "8080:8080"

    # Running default command.
    # This prepares the WARs and also executes the default command of the Docker image
    working_dir: /usr/local/tomcat
    command: ["catalina.sh run"]
