name: test
on: [push]
jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: npm install
      - run: npm test

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download backend
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "wiris/plugins"
          version: "tags/latest"
          file: "java-generic_wiris.zip"
          token: ${{ secrets.GH_CICD_TOKEN }}

      - name: Deploy backend
        run: |
          unzip "java-generic_wiris.zip" -d "java-generic_wiris"
          unzip "java-generic_wiris/pluginwiris_engine.war" -d "pluginwiris_engine"
          cd docker/java
          EDITOR=generic docker-compose up -d
          curl -u test:testpass "http://localhost:8080/manager/text/deploy?path=/pluginwiris_engine&update=true&config=&war=${{ env.GITHUB_WORKSPACE }}/pluginwiris_engine"
