name: test
on: [push]
jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: npm install
      - run: npm test

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Download backend
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: wiris/plugins
          version: "latest"
          file: java-generic_wiris.zip
          token: ${{ secrets.GH_CICD_TOKEN }}
